Repository rancher/docs, pull requests merged in 2019-12, with the labels that each got.

#2042 Fix link in Google OAuth doc
  content/rancher/v2.x/en/admin-settings/authentication/google/_index.md
Labels: [zube]: In Review

#2044 Update Helm version required for 1.16
  content/rancher/v2.x/en/installation/helm-version/_index.md
Labels: [zube]: In Review

#2000 broken links
  content/rancher/v2.x/en/admin-settings/_index.md
  content/rancher/v2.x/en/catalog/_index.md
  content/rancher/v2.x/en/cluster-admin/tools/istio/setup/enable-istio-in-cluster/_index.md
  content/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/_index.md
  content/rancher/v2.x/en/project-admin/tools/alerts/_index.md
Labels: [zube]: In Review, bug

#1637 Update and clarify docs on global and cluster permissions
  content/rancher/v2.x/en/admin-settings/authentication/ad/_index.md
  content/rancher/v2.x/en/admin-settings/authentication/openldap/_index.md
  content/rancher/v2.x/en/admin-settings/config-private-registry/_index.md
  content/rancher/v2.x/en/admin-settings/rbac/cluster-project-roles/_index.md
  content/rancher/v2.x/en/admin-settings/rbac/global-permissions/_index.md
  content/rancher/v2.x/en/cluster-provisioning/rke-clusters/node-pools/vsphere/provisioning-vsphere-clusters/_index.md
  content/rancher/v2.x/en/cluster-provisioning/rke-clusters/node-pools/vsphere/provisioning-vsphere-clusters/enabling-uuids/_index.md
  content/rancher/v2.x/en/faq/technical/_index.md
  content/rancher/v2.x/en/faq/telemetry/_index.md
  content/rancher/v2.x/en/project-admin/resource-quotas/_index.md
  content/rancher/v2.x/en/security/_index.md
  content/rancher/v2.x/en/security/hardening-2.1/_index.md
  content/rancher/v2.x/en/security/hardening-2.2/_index.md
  content/rancher/v2.x/en/security/hardening-2.3/_index.md
Labels: [zube]: In Review

#2058 Small tweak to K3s airgap page
  content/k3s/latest/en/installation/airgap/_index.md
Labels: K3s

#2063 Add new network-options page to Install section
  content/k3s/latest/en/installation/network-options/_index.md
  content/k3s/latest/en/networking/_index.md
Labels: K3s

#2065 Fix broken hyperlink on networking-options page
  content/k3s/latest/en/installation/network-options/_index.md
Labels: K3s

#2054 Align installation requirements with terms of service
  content/rancher/v2.x/en/cluster-provisioning/node-requirements/_index.md
  content/rancher/v2.x/en/installation/requirements/_index.md
Labels: [zube]: In Review

#1960 Revise architecture diagram and overview section
  content/rancher/v2.x/en/catalog/_index.md
  content/rancher/v2.x/en/cluster-admin/kubeconfig/_index.md
  content/rancher/v2.x/en/cluster-provisioning/_index.md
  content/rancher/v2.x/en/cluster-provisioning/rancher-agents/_index.md
  content/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/_index.md
  content/rancher/v2.x/en/contributing/_index.md
  content/rancher/v2.x/en/installation/air-gap/_index.md
  content/rancher/v2.x/en/installation/choosing-installation/_index.md
  content/rancher/v2.x/en/installation/ha/_index.md
  content/rancher/v2.x/en/installation/server-tags/_index.md
  content/rancher/v2.x/en/overview/_index.md
  content/rancher/v2.x/en/overview/architecture-recommendations/_index.md
  content/rancher/v2.x/en/overview/architecture/_index.md
  content/rancher/v2.x/en/overview/concepts/_index.md
  static/img/rancher/rancher-architecture-cluster-controller.svg
  static/img/rancher/rancher-architecture-node-roles.svg
  static/img/rancher/rancher-architecture-rancher-api-server.svg
  static/img/rancher/rancher-architecture-rancher-components.svg
  static/img/rancher/rancher-architecture-separation-of-rancher-server.svg
  static/img/rancher/rancher-architecture.svg
Labels: [zube]: Working

#2088 Document RKE event rate limiting feature
  content/rke/latest/en/config-options/_index.md
  content/rke/latest/en/config-options/rate-limiting/_index.md
Labels: [zube]: In Review

#2089 Document audit log feature of RKE
  content/rke/latest/en/config-options/_index.md
  content/rke/latest/en/config-options/audit-log/_index.md
Labels: [zube]: In Review

#2093 Remove dash from suggested HA db name
  content/k3s/latest/en/_index.md
  content/k3s/latest/en/installation/datastore/_index.md
Labels: K3s

#1911 Update RKE upgrade documentation
  content/rke/latest/en/upgrades/_index.md
Labels: RKE, Upgrades, [zube]: Backlog

#2031 Quick deploy roles for AWS IAM
  content/rke/latest/en/config-options/cloud-providers/aws/_index.md
Labels: RKE, [zube]: In Review

#2060 Add Docker installation scripts to docs
  content/rancher/v2.x/en/installation/requirements/_index.md
  content/rancher/v2.x/en/installation/requirements/installing-docker/_index.md
Labels: [zube]: Backlog

#2100 Explain how to use custom global permissions with groups
  content/rancher/v2.x/en/admin-settings/_index.md
  content/rancher/v2.x/en/admin-settings/rbac/default-custom-roles/_index.md
  content/rancher/v2.x/en/admin-settings/rbac/global-permissions/_index.md
Labels: [zube]: In Review

#2112 Update security docs for Rancher v2.4
  content/rancher/v2.x/en/security/_index.md
  content/rancher/v2.x/en/security/security-scan/_index.md
Labels: [zube]: In Review

#1902 Say to check ingress-nginx upgrade policy
  content/rancher/v2.x/en/cluster-admin/editing-clusters/_index.md
  content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/cce/_index.md
  content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/tke/_index.md
  content/rancher/v2.x/en/installation/ha/kubernetes-rke/_index.md
  content/rancher/v2.x/en/upgrades/upgrades/ha/_index.md
Labels: [zube]: In Review
