Repository rancher/docs, pull requests merged in 2020-12, with the labels that each got.

#2870 Update _index.md
  content/k3s/latest/en/installation/network-options/_index.md
Labels: K3s

#2825 Adapt default value for noProxy helm chart variable
  content/rancher/v2.x/en/installation/other-installation-methods/behind-proxy/install-rancher/_index.md
  content/rancher/v2.x/en/installation/other-installation-methods/single-node-docker/proxy/_index.md
  content/rancher/v2.x/en/installation/resources/chart-options/_index.md
Labels: [zube]: In Review

#2869 Update Windows and RBAC sections in Logging
  content/rancher/v2.x/en/logging/v2.5/_index.md
Labels: Logging/monitoring

#2887 Add description for clusters with private-only API
  content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
Labels: [zube]: Working

#2878 Added cgroup documentation for raspbian
  content/k3s/latest/en/advanced/_index.md
Labels: K3s

#2637 Cleanup Rancher port requirements
  content/rancher/v2.x/en/cluster-provisioning/node-requirements/_index.md
  content/rancher/v2.x/en/installation/requirements/_index.md
  content/rancher/v2.x/en/installation/requirements/ports/_index.md
  content/rancher/v2.x/en/installation/requirements/ports/common-ports-table/index.md
  content/rancher/v2.x/en/installation/resources/advanced/firewall/_index.md
  layouts/shortcodes/ports-custom-nodes.html
  layouts/shortcodes/ports-iaas-nodes.html
  layouts/shortcodes/ports-imported-hosted.html
  static/img/rancher/port-communications.svg
Labels: Waiting for QA/verification, [zube]: In Review

#2907 Document port requirements for RancherD install
  content/rancher/v2.x/en/installation/requirements/ports/_index.md
Labels: [zube]: In Review

#2903 Promote etcd to stable as of 1.19.5
  content/k3s/latest/en/installation/ha-embedded/_index.md
Labels: [zube]: In Review

#2912 [k3s] Update system-upgrade-controller to v0.6.2
  content/k3s/latest/en/upgrades/automated/_index.md
Labels: K3s

#2908 Document that all-in-one Jaeger is bundled with Istio
  content/rancher/v2.x/en/istio/v2.5/_index.md
Labels: [zube]: In Review

#2914 Include description for security groups and private API
  content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
Labels: [zube]: In Review

#2927 Cis v2 scheduling, alerting and also custom benchmark docs
  content/rancher/v2.x/en/cis-scans/v2.5/_index.md
  content/rancher/v2.x/en/cis-scans/v2.5/custom-benchmark/_index.md
  content/rancher/v2.x/en/cis-scans/v2.5/rbac/_index.md
Labels: [zube]: In Review

#2930 Document iptables and container-selinux config for RancherD install on SELinux
  content/rancher/v2.x/en/installation/install-rancher-on-linux/_index.md
  content/rancher/v2.x/en/installation/requirements/_index.md
Labels: [zube]: In Review

#2932 Add example for CIS alerts in Alertmanager doc
  content/rancher/v2.x/en/cis-scans/v2.5/_index.md
  content/rancher/v2.x/en/monitoring-alerting/v2.5/configuration/alertmanager/_index.md
Labels: [zube]: In Review

#2851 Create separate page documenting registered clusters
  content/rancher/v2.x/en/cluster-provisioning/_index.md
  content/rancher/v2.x/en/cluster-provisioning/imported-clusters/_index.md
  content/rancher/v2.x/en/cluster-provisioning/registered-clusters/_index.md
  layouts/shortcodes/result_import-cluster.html
Labels: [zube]: In Review

#2824 add flannel backend port configuration example
  content/rke/latest/en/config-options/add-ons/network-plugins/_index.md
Labels: [zube]: In Review
