Repository rancher/docs, pull requests merged in 2020-11, with the labels that each got.

#2578 Use the installCRDs option for cert-manager
  content/rancher/v2.x/en/installation/install-rancher-on-k8s/_index.md
Labels: [zube]: In Review

#2579 Update airgapped installation documentation to newer version of cert manager
  content/rancher/v2.x/en/installation/other-installation-methods/air-gap/install-rancher/_index.md
  content/rancher/v2.x/en/installation/other-installation-methods/air-gap/populate-private-registry/_index.md
Labels: Waiting for QA/verification, [zube]: In Review

#2837 Update OS requirements section in K3s docs
  content/k3s/latest/en/installation/installation-requirements/_index.md
Labels: [zube]: In Review

#2836 Document K3s resource profiling
  content/k3s/latest/en/installation/installation-requirements/_index.md
  content/k3s/latest/en/installation/installation-requirements/resource-profiling/_index.md
Labels: [zube]: In Review

#2823 Update section about K3s support for SELinux
  content/k3s/latest/en/advanced/_index.md
Labels: [zube]: In Review

#2828 Remove Longhorn no longer needed storageclass info
  content/k3s/latest/en/storage/_index.md
Labels: K3s, Longhorn, [zube]: In Review

#2863 Add docs to persist Grafana dashboards
  content/rancher/v2.x/en/monitoring-alerting/v2.5/_index.md
  content/rancher/v2.x/en/monitoring-alerting/v2.5/persist-grafana/_index.md
  content/rancher/v2.x/en/monitoring-alerting/v2.5/rbac/_index.md
Labels: [zube]: In Review

#2873 Use newer klipper-helm image
  content/k3s/latest/en/helm/_index.md
Labels: K3s
