Repository rancher/docs, pull requests merged in 2020-06, with the labels that each got.

#2277 Brings some missing information in the documenation
  content/rke/latest/en/installation/certs/_index.md
Labels: SSL certs, [zube]: In Review

#1529 Create doc for prometheus metrics usage
  content/rancher/v2.x/en/cluster-admin/tools/monitoring/custom-metrics/_index.md
Labels: Logging/monitoring

#2548 Update NLB setup doc for K3s Rancher installs
  content/rancher/v2.x/en/installation/options/nlb/_index.md
Labels: [zube]: In Review

#2549 Link to details about auto-deployed manifests for K3s
  content/k3s/latest/en/architecture/_index.md
Labels: [zube]: In Review

#2523 Improve docs for running K3s with Docker
  content/k3s/latest/en/advanced/_index.md
Labels: [zube]: In Review
