Repository rancher/docs, pull requests merged in 2020-01, with the labels that each got.

#2110 Updated info about using kubeconfig
  content/k3s/latest/en/configuration/_index.md
Labels: K3s

#2161 Read-only system project access is needed for configuring Istio viz access
  .vscode/settings.json
  content/rancher/v2.x/en/cluster-admin/tools/istio/rbac/_index.md
Labels: [zube]: In Review

#2165 Add info about helm3 and migrating from helm2
  content/k3s/latest/en/advanced/_index.md
Labels: K3s

#2133 Change title for section on cleaning nodes
  content/rancher/v2.x/en/cluster-admin/cleaning-cluster-nodes/_index.md
Labels: [zube]: In Review

#2143 Add RKE command to show available K8s versions
  content/rke/latest/en/config-options/_index.md
  content/rke/latest/en/upgrades/_index.md
Labels: [zube]: Working

#2172 add the reason and proper steps for upgrading both rancher and cert-manager
  content/rancher/v2.x/en/installation/options/upgrading-cert-manager/_index.md
  content/rancher/v2.x/en/installation/options/upgrading-cert-manager/helm-2-instructions/_index.md
  content/rancher/v2.x/en/upgrades/upgrades/ha/_index.md
Labels: [zube]: In Review

#2174 Added section node configuration
  content/rancher/v2.x/en/best-practices/deployment-types/_index.md
Labels: [zube]: In Review

#2134 Document detaching clusters from Rancher
  content/rancher/v2.x/en/removing-rancher/_index.md
  content/rancher/v2.x/en/system-tools/_index.md
Labels: [zube]: Working

#2204 Clarify versioning of CIS benchmark assessment and hardening guides
  content/rancher/v2.x/en/cluster-provisioning/node-requirements/_index.md
  content/rancher/v2.x/en/security/_index.md
  content/rancher/v2.x/en/security/benchmark-2.1/_index.md
  content/rancher/v2.x/en/security/benchmark-2.2/_index.md
  content/rancher/v2.x/en/security/benchmark-2.3.3/_index.md
  content/rancher/v2.x/en/security/benchmark-2.3/_index.md
  content/rancher/v2.x/en/security/hardening-2.1/_index.md
  content/rancher/v2.x/en/security/hardening-2.2/_index.md
  content/rancher/v2.x/en/security/hardening-2.3.3/_index.md
  content/rancher/v2.x/en/security/hardening-2.3/_index.md
Labels: [zube]: In Review
