Repository rancher/docs, pull requests merged in 2021-05, with the labels that each got.

#3175 Document project network isolation on any cluster + CNI
  content/rancher/v2.5/en/cluster-admin/editing-clusters/_index.md
  content/rancher/v2.5/en/cluster-admin/projects-and-namespaces/_index.md
  content/rancher/v2.5/en/cluster-provisioning/rke-clusters/options/_index.md
  content/rancher/v2.5/en/istio/configuration-reference/_index.md
  content/rancher/v2.5/en/istio/configuration-reference/canal-and-project-network/_index.md
  content/rancher/v2.5/en/istio/setup/enable-istio-in-cluster/_index.md
Labels: [zube]: In Review

#3225 Loggingv2
  content/rancher/v2.5/en/logging/_index.md
Labels: [zube]: In Review

#3021 k3s docs for traefik v2
  content/k3s/latest/en/networking/_index.md
Labels: K3s, [zube]: K3S Inbox

#3237 Add SELinux docs
  content/rancher/v2.5/en/logging/_index.md
  content/rancher/v2.5/en/security/_index.md
  content/rancher/v2.5/en/security/rancher-2.5/_index.md
  content/rancher/v2.5/en/security/selinux/_index.md
Labels: [zube]: In Review

#3213 Update K3s security documentation.
  content/k3s/latest/en/security/_index.md
  content/k3s/latest/en/security/hardening_guide/_index.md
Labels: Security, [zube]: Rancher Inbox

#3239 Merge staging to master
  content/_index.html
  content/rancher/v2.5/en/cluster-admin/editing-clusters/_index.md
  content/rancher/v2.5/en/cluster-admin/projects-and-namespaces/_index.md
  content/rancher/v2.5/en/cluster-provisioning/_index.md
  content/rancher/v2.5/en/cluster-provisioning/cluster-capabilities-table/index.md
  content/rancher/v2.5/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
  content/rancher/v2.5/en/cluster-provisioning/hosted-kubernetes-clusters/gke/_index.md
  content/rancher/v2.5/en/cluster-provisioning/hosted-kubernetes-clusters/gke/config-reference/_index.md
  content/rancher/v2.5/en/cluster-provisioning/hosted-kubernetes-clusters/gke/private-clusters/_index.md
  content/rancher/v2.5/en/cluster-provisioning/hosted-kubernetes-clusters/syncing/_index.md
  content/rancher/v2.5/en/cluster-provisioning/registered-clusters/_index.md
  content/rancher/v2.5/en/cluster-provisioning/rke-clusters/options/_index.md
  content/rancher/v2.5/en/cluster-provisioning/rke-clusters/windows-clusters/_index.md
  content/rancher/v2.5/en/faq/removing-rancher/_index.md
  content/rancher/v2.5/en/installation/install-rancher-on-k8s/_index.md
  content/rancher/v2.5/en/installation/install-rancher-on-k8s/gke/_index.md
  content/rancher/v2.5/en/installation/install-rancher-on-k8s/upgrades/_index.md
  content/rancher/v2.5/en/installation/install-rancher-on-k8s/upgrades/air-gap-upgrade/_index.md
  content/rancher/v2.5/en/installation/other-installation-methods/air-gap/install-rancher/_index.md
  content/rancher/v2.5/en/installation/other-installation-methods/air-gap/install-rancher/docker-install-commands/_index.md
  content/rancher/v2.5/en/installation/resources/feature-flags/_index.md
  content/rancher/v2.5/en/istio/configuration-reference/_index.md
  content/rancher/v2.5/en/istio/configuration-reference/canal-and-project-network/_index.md
  content/rancher/v2.5/en/istio/setup/enable-istio-in-cluster/_index.md
  content/rancher/v2.5/en/logging/_index.md
  content/rancher/v2.5/en/monitoring-alerting/_index.md
  content/rancher/v2.5/en/monitoring-alerting/configuration/alertmanager/_index.md
  content/rancher/v2.5/en/monitoring-alerting/persist-grafana/_index.md
  content/rancher/v2.5/en/monitoring-alerting/rbac/_index.md
  content/rancher/v2.5/en/monitoring-alerting/windows-clusters/_index.md
  content/rancher/v2.5/en/security/_index.md
  content/rancher/v2.5/en/security/rancher-2.5/_index.md
  content/rancher/v2.5/en/security/selinux/_index.md
  content/rancher/v2.x/en/_index.md
  content/rke/latest/en/config-options/add-ons/_index.md
  content/rke/latest/en/config-options/add-ons/dns/_index.md
  content/rke/latest/en/config-options/add-ons/ingress-controllers/_index.md
  content/rke/latest/en/config-options/add-ons/metrics-server/_index.md
  content/rke/latest/en/config-options/add-ons/network-plugins/_index.md
Labels: [zube]: Working

#3247 Create Windows Linux feature parity matrix
  content/rancher/v2.5/en/cluster-provisioning/rke-clusters/windows-clusters/windows-parity/_index.md
Labels: [zube]: In Review

#3183 Add install Rancher on AKS
  content/rancher/v2.5/en/installation/install-rancher-on-k8s/aks/_index.md
Labels: [zube]: In Review

#3262 Fix kubectl patch command for v2.5.x in update CA docs
  content/rancher/v2.5/en/installation/resources/update-ca-cert/_index.md
Labels: internal

#3264 Add "Mutable" indicator for GKE config-reference
  content/rancher/v2.5/en/cluster-provisioning/hosted-kubernetes-clusters/gke/config-reference/_index.md
Labels: [zube]: In Review

#3278 Update Istio uninstall steps
  content/rancher/v2.5/en/istio/disabling-istio/_index.md
Labels: [zube]: In Review

#3277 Add PagerDuty example for Rancher <2.5.4
  content/rancher/v2.5/en/monitoring-alerting/configuration/alertmanager/_index.md
Labels: [zube]: In Review

#3284 Fix openssl certificate generation command in ADFS docs
  content/rancher/v2.5/en/admin-settings/authentication/microsoft-adfs/rancher-adfs-setup/_index.md
  content/rancher/v2.x/en/admin-settings/authentication/microsoft-adfs/rancher-adfs-setup/_index.md
Labels: [zube]: In Review
