Repository rancher/docs, pull requests merged in 2021-04, with the labels that each got.

#3064 Add cattle-logging ns recreation troubleshooting
  content/rancher/v2.x/en/logging/v2.5/_index.md
Labels: [zube]: In Review

#3135 k3s: add note about firewalld for el
  content/k3s/latest/en/advanced/_index.md
  content/k3s/latest/en/installation/installation-requirements/_index.md
Labels: K3s

#3170 Add missing quotes in k3s kube-dashboard install instruction
  content/k3s/latest/en/installation/kube-dashboard/_index.md
Labels: K3s, [zube]: K3S Inbox

#3212 Make hosted cluster syncing explanation generic
  content/rancher/v2.5/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
  content/rancher/v2.5/en/cluster-provisioning/hosted-kubernetes-clusters/gke/_index.md
  content/rancher/v2.5/en/cluster-provisioning/hosted-kubernetes-clusters/syncing/_index.md
Labels: [zube]: In Review

#3166 Update Rancher requirements to include RKE2 installs
  content/rancher/v2.5/en/installation/requirements/_index.md
  content/rancher/v2.5/en/installation/resources/k8s-tutorials/ha-rke2/_index.md
  content/rancher/v2.x/en/installation/requirements/_index.md
  content/rancher/v2.x/en/installation/resources/k8s-tutorials/ha-RKE2/_index.md
Labels: [zube]: In Review

#3209 Add rancher-alerting-drivers
  content/rancher/v2.5/en/monitoring-alerting/configuration/alertmanager/_index.md
Labels: [zube]: In Review

#3208 Add Monitoring v2 SSL instructions for email/webhook receivers
  content/rancher/v2.5/en/monitoring-alerting/_index.md
Labels: [zube]: In Review

#3228 fix the minimal SMS receiver configuration
  content/rancher/v2.5/en/monitoring-alerting/configuration/alertmanager/_index.md
Labels: [zube]: Rancher Inbox
